language: python
python:
  - '3.8'
before_install:
  - openssl aes-256-cbc -K $encrypted_5b2b69c980b5_key -iv $encrypted_5b2b69c980b5_iv
    -in tests/secrets.env.enc -out tests/secrets.env -d
  - set -a; . tests/secrets.env; set +a
install:
  - pip install -e .
script:
  - python -m unittest discover -s tests
deploy:
  provider: pypi
  user: "retxxxirt"
  password:
    secure: "fs6fmbtgSX5ckKD5okIoscVr5sbLiAGz+i6gQJpranrXHBMENXPTDlCFO/QDi16tx9Mk7PSHfg0yg0EengA8AfBjCDBiAtaMx89/wYaBCKwDamh7zhFMuCVWWq8mgBVGij73sBxB1vSPeZoEiM0Ror/AKNGZbi5Be1MxsF+NUBs6dXsS66Jk+s1IeeXnLiwGEPNEq0japdMpB8Kh3XNX+TA1QACrWmpyc6YIMPuu9DZ/MTQFzIvji0U3DkPTVB9+waQ5HVG+q4HtPll/fT5dn48iZDIQQReUpeLRYzyKK1l57X7WAKs34g3ATk5tcCbD3rPgxlgZQFce0BP0eqfpjeftpdsNqkc/saEcFCmE3sAMX4I2wtaCz77y4dICtZfhqOXPOv0nzMKa/WrWpSRcFTPumWPOYtVLK8uALzkeil+30cNJfIX+ItuOI3bRjnB0Q6m0cwAjXSrwERSJhCAUIk3J3D3un4XpPgUSfwOpZFk9j+7jOWYFHXqBgx0HJO+QINTAY6UrqIFSq9GdsFXmT7UubwemO2TFaiLfImTvjACKDVN0L4/+13lePrXDr4u5Rf8DfFEHeQzgMPq2KzL3O3SeEM+QenGYb8p/l4DZxniBFUgaTOVX0cvqk46PQCamaBfAYlruJY8fuSWQq+MCJIZLak7veqnF1Zpy+jmyuxI="
  on:
    branch: production